<div class="row">
    <div class="col-md-12">
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Chuyên mục</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/category/search">Quản lý chuyên mục</a></li>
                    <li><a target="_blank" href="/category/new">Thêm chuyên mục</a></li>
                </ul>
              </div>
            </div>
        </div>
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Tin tức</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/new/search">Quản trị tin tức</a></li>
                    <li><a target="_blank" href="/new/new">Thêm tin tức mới</a></li>
                </ul>
              </div>
            </div>
        </div>
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Người dùng</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/user/search">Quản trị người dùng</a></li>
                    <li><a target="_blank" href="/user/search-roles">Quyền</a></li>
                </ul>
              </div>
            </div>
        </div>                
    </div>
    <div class="col-md-12">
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Video</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/video/search">Quản trị video</a></li>
                    <li><a target="_blank" href="/video/new">Thêm tin video</a></li>
                </ul>
              </div>
            </div>
        </div>  
        
        <div class='col-xs-6 col-sm-4'>
	        <div class="panel panel-default">
	          <div class="panel-heading">
	            <h3 class="panel-title">Configurations</h3>
	          </div>
	          <div class="panel-body admin-panel-body">
	           <ul>
	        	   <li><a href='/conf/new'>New Conf</a></li>
		    	   <li><a href='/conf/search'>List Conf</a></li>
	    	   </ul>
	          </div>
	        </div>
		</div>
        <?php /*
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Samx</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/samx/search">Search samx</a></li>
                    <li><a target="_blank" href="/samx/search-comment">Search samx comments</a></li>
                    <li><a target="_blank" href="/samx/new">New samx</a></li>
                </ul>
              </div>
            </div>
        </div>  
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Common stuff</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/sitex/create-module">Create module</a></li>
                    <li><a target="_blank" href="/queue/overview">Queue</a></li>
                    <li>	       <a href='/fwdoc/queue'>queue docs</a> </li>
                    <li>	       <a href='/fwdoc/index'>all docs</a> </li>
                    <li><a href='/fwdoc/todo'>todos</a></li>
                    <li><a href='/site/admin'>Admin</a></li>    	   
                    <li><a href='/sitex/'>Sitex</a></li>    
                </ul>
              </div>
            </div>
        </div>    
        */ ?>                  
    </div>
</div>