<div class=' well'>
    <h1> Chuyên mục </h1>
    <ul>
    <li><a target="_blank" href="/category/search">Quản lý chuyên mục</a></li>
    <li><a target="_blank" href="/category/new">Thêm chuyên mục</a></li>
    </ul>
</div>

<div class=' well'>
    <h1> Người dùng</h1>
    <ul>
    <li><a target="_blank" href="/user/search">Quản trị người dùng</a></li>
    <li><a target="_blank" href="/user/search-roles">Quyền</a></li>
    </ul>
</div>

<div class=' well'>
    <h1> Tin tức</h1>
    <ul>
    <li><a target="_blank" href="/new/search">Quản trị tin tức</a></li>
    <li><a target="_blank" href="/new/new">Thêm tin tức mới</a></li>
    </ul>
</div>

<div class=' well'>
    <h1> Video</h1>
    <ul>
    <li><a target="_blank" href="/video/search">Quản trị video</a></li>
    <li><a target="_blank" href="/video/new">Thêm tin video</a></li>
    </ul>
</div>

<div class=' well'>
    <h1> Samx</h1>
    <ul>
    <li><a target="_blank" href="/samx/search">Search samx</a></li>
    <li><a target="_blank" href="/samx/search-comment">Search samx comments</a></li>
    <li><a target="_blank" href="/samx/new">New samx</a></li>
    </ul>
</div>
<div class=' well'>
    <h1> Common stuff</h1>
    <ul>
    <li><a target="_blank" href="/sitex/create-module">Create module</a></li>
    <li><a target="_blank" href="/queue/overview">Queue</a></li>
    <li>	       <a href='/fwdoc/queue'>queue docs</a> </li>
    <li>	       <a href='/fwdoc/index'>all docs</a> </li>
    <li><a href='/fwdoc/todo'>todos</a></li>
     <li><a href='/site/admin'>Admin</a></li>    	   
     <li><a href='/sitex/'>Sitex</a></li>    
    </ul>
    
</div>
