<div class="row">
    <div class="col-md-12">
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Chuyên mục</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/category/search">Quản lý chuyên mục</a></li>
                    <li><a target="_blank" href="/category/new">Thêm chuyên mục</a></li>
                </ul>
              </div>
            </div>
        </div>
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Tin tức</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/new/search">Quản trị tin tức</a></li>
                    <li><a target="_blank" href="/new/new">Thêm tin tức mới</a></li>
                </ul>
              </div>
            </div>
        </div>
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Người dùng</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/user/search">Quản trị người dùng</a></li>
                    <li><a target="_blank" href="/user/search-roles">Quyền</a></li>
                </ul>
              </div>
            </div>
        </div>                
    </div>
    <div class="col-md-12">
        <div class='col-xs-6 col-sm-4'>
            <div class="panel panel-default">
              <div class="panel-heading">Video</div>
              <div class="panel-body">
                <ul>
                    <li><a target="_blank" href="/video/search">Quản trị video</a></li>
                    <li><a target="_blank" href="/video/new">Thêm tin video</a></li>
                </ul>
              </div>
            </div>
        </div>  
        
        <div class='col-xs-6 col-sm-4'>
	        <div class="panel panel-default">
	          <div class="panel-heading">
	            <h3 class="panel-title">Configurations</h3>
	          </div>
	          <div class="panel-body admin-panel-body">
	           <ul>
	        	   <li><a href='/conf/new'>New Conf</a></li>
		    	   <li><a href='/conf/search'>List Conf</a></li>
	    	   </ul>
	          </div>
	        </div>
		</div>
		
		<div class='col-xs-6 col-sm-4'>
		    <div class="panel panel-default">
	          <div class="panel-heading">
	            <h3 class="panel-title">Phản hồi</h3>
	          </div>
	          <div class="panel-body admin-panel-body">
	            <ul>
	            	<li><a href="/feedback/search" target="_blank">Quản lý phản hồi</a></li>
	            	<li><a href="/feedback/new" target="_blank">Tạo phản hồi mới mới</a></li>
	    	    </ul>
	          </div>
       	 </div>
		</div>
    </div>
    
    <div class="col-md-12">
   		 <div class='col-xs-6 col-sm-4'>
		    <div class="panel panel-default">
	          <div class="panel-heading">
	            <h3 class="panel-title">Đặt hàng</h3>
	          </div>
	          <div class="panel-body admin-panel-body">
	            <ul>
	            	<li><a href="/bill/search" target="_blank">Quản lý đơn đặt hàng</a></li>
	            	<li><a href="/bill/new" target="_blank">Tạo đơn mới</a></li>
	    	    </ul>
	          </div>
       	 </div>
		</div>
    </div>
    
</div>