<?php 
	$lu = Zend_Registry::get('user');
	$news = $this->news;
	$bestNews = $this->bestNews;
	$videos = $this->videos;
	$tinNhanh = $this->tinNhanh;
?>
<div style='min-height: 400px;'>
		<div class='row'>
			<div class='col-md-7'>
				<div id="content-main" class='dieukhoan'>
					<div class="title-newsdetail " 
							style="text-align:center; font-size:18px; ">Điều khoản sử dụng</div>
					    <div class="content-news fl">
							<div class='title'>
								1 - Sử dụng trang web của chúng tôi
							</div>
							<div class='content'>
								 Website công ty <a href="<?php echo SITE_URL?>">Cổ Phần GoldStar Việt Nam</a>
								đăng tải các thông tin tiện ích tin học, các tài liệu tham khảo liên quan đến thuế, kế toán, luật pháp, nghị định.  Một số thông tin cơ bản của các đối tác và những tài liệu nhằm cung cấp cho người tiêu dùng sử dụng tham khảo những thông tin hữu ích. 
								Thông tin chỉ mang tính tham khảo chúng tôi không chịu trách nhiệm khi quý vị sử dụng vào mục đích khác
								<br>
								Việc người truy cập và sử dụng website chúng tôi là đã chấp thuận những điều kiện và điều khoản của website
								<a href="<?php echo SITE_URL?>"><b><u>Công Ty Cổ Phần GoldStar Việt Nam</u></b></a>
							</div>
							<div class='title'>
								Logo & Hình ảnh thuộc công ty
								</div>
							<div class='content'>
								Việc sử dụng logo và hình ảnh của chúng tôi trong bất kỳ trường hợp nào đều phải 
								thông qua sự đồng ý của goldstar.com.vn. 
								</div>
							<div class='title'>
								3 - Liên kết và kết nối
								</div>
							<div class='content'>
								Chúng tôi khuyến khích người dùng chia sẻ thông tin và liên kết tới trang website 
								công ty quảng cáo GoldStar Việt Nam. Tuy nhiên, Chúng tôi không chấp nhận hình thức nạp 
								website goldstar.com.vn vào khung website (iframe) của đơn vị khác mà phải giúp người dùng 
								sử dụng web goldstar.com.vn tràn đầy trình duyệt. 
								</div>
							<div class='title'>
								4 - Nguồn tài nguyên bên ngoài (hình ảnh, logo, liên kết, videos, âm thanh v.v...)
								</div>
							<div class='content'>
								Chúng tôi cung cấp cho người dùng một nguồn số tài nguyên nhất định trên website phục vụ 
								cho việc tham khảo & học tập không phải mục đích kinh doanh. Tuy nhiên không bao gồm tất cả 
								hình ảnh, logo, liên kết, videos, âm thanh v.v... hoàn toàn không được lưu trữ hoặc 
								upload bởi chúng tôi. Mọi mục đích sử dụng trái phép hoặc vi phạm bản quyền,
								 người dùng sẽ phải tuân thủ độc lập với cá nhân / đơn vị nắm giữ bản quyền thực sự 
								 ( không phải với chúng tôi ). 
								</div>
							<div class='title'>
								5 - Bản quyền - tác quyền bên ngoài
								</div>
							<div class='content'>
								Nếu bạn cảm thấy nội dung nào liên quan đến vấn đề sở hữu, bản quyền, 
								tác quyền thuộc về bạn, hãy thông báo cho chúng tôi và chúng tôi sẽ xem xét
								 để gỡ bỏ hoặc trích dẫn thông tin của bạn theo yêu cầu trong vòng 7 ngày kể 
								 từ ngày nhận được email. Để tiến trình diễn ra nhanh chóng và thuận tiện,
								  khi các bạn gửi yêu cầu gỡ bỏ nội dung hoặc thêm thông tin vui lòng gửi 
								  theo các thông tin sau:

								+ Họ và Tên:
								
								+ Email liên lạc:
								
								+ Bằng chứng bạn sở hữu chủ quyền, bản quyền, tác quyền, độc quyền nội dung mà bạn muốn chúng tôi gỡ bỏ, bao gồm file gốc, lisence, certificate , digital signature v.v.... mọi thứ mà chúng tôi có thể căn cứ và xác định chủ quyền thuộc về bạn.
								
								+ Yêu cầu bạn mong muốn: Gỡ bỏ, thêm thông tin, links trích dẫn v.v.... 
								</div>
							<div class='title'>
								6 - Nguồn thông tin
								</div>
							<div class='content'>
								Thông tin có tại goldstar.com.vn ngoài những tin quảng cáo thuộc goldstar.com.vn, 
								các nội dung thuộc nguồn bên ngoài luôn được đăng tác giả, nguồn tin và được liên kết 
								tới các nguồn cung cấp thông tin như một lợi ích chia sẻ trên internet. 
								Nếu vì một lý do nào đó chúng tôi đăng sai hoặc 
								thiếu thông tin các bạn vui lòng làm theo mục 5 phía trên.
	
								Sis.vn cũng yêu cầu các đơn vị khác trích nguồn dẫn goldstar.com.vn
								 khi sử dụng những thông tin có tại website của chúng tôi. 
								</div>
							<div class='title'>
								7 - Nghĩa vụ người dùng
								</div>
							<div class='content'>
								Chúng tôi cung cấp cho người dùng quyền truy cập các thông tin về các
								 sản phẩm quảng cáo, lĩnh vực hoạt động của chúng tôi và một số thông tin khác 
								 hoàn toàn miễn phí. Tuy nhiên, các bạn phải tuân thủ một số quy định nghiêm ngặt sau:

								- Không tuyên truyền, xuyên tạc hoặc vi phạm hiến pháp, pháp luật của nhà nước Việt Nam.
								
								- Không tuyên truyền các nội dung liên quan các tôn giáo hay kì thị chủng tộc
								
								- Không quảng cáo, quảng bá vi phạm luật quảng cáo
								
								Tất cả các nội dung vi phạm sẽ bị chúng tôi xóa bỏ mà không cần thông báo ở ngay thời điểm chúng tôi
								 phát hiện.
								
								Thông tin của người dùng sẽ được chúng tôi bảo mật. Tuy nhiên, người dùng có thể sẽ bị truy cứu
								 theo pháp luật hiện hành nếu vi phạm các điều trên. Chúng tôi buộc phải cung cấp các thông tin cần thiết cho cơ quan có thẩm quyền khi được yêu cầu. Người dùng hoàn toàn chịu trách nhiệm với thông tin mình đăng tải trên goldstar.com.vn 
								</div>
							<div class='title'>
								8 - Virus - bảo vệ - Tác động thứ 3
								</div>
							<div class='content'>
								Chúng tôi sử dụng website như một kênh thông tin truyền thông để quảng bá thương hiệu, 
								giới thiệu sản phẩm và tạo một môi trường internet bổ ích cho việc tham khảo và học tập. 
								Chúng tôi luôn nỗ lực hết mình để hướng tới người sử dụng được hiệu quả và an toàn nhất 
								khi truy cập website.
	
								Tuy nhiên, với thực trạng Virus & hacker đa dạng và khó kiểm soát hiện nay,
								 chúng tôi sẽ không chịu bất kỳ trách nhiệm nào đối với mọi sự tổn thất,
								  gián đoạn hoăc thiệt hại nào khi một chương trình, tệp tin... được tải
								   về máy tính của người dùng mà đường dẫn là một website khác và tài liệu, 
								   thông tin của chúng tôi chỉ mang tính tham khảo phục vụ học tập.
								
								Sử dụng những phần mềm diệt virut trên máy tính khi truy cập internet luôn là 
								sự lựa chọn thông minh của người dùng. 
								</div>
							<div class='title'>
								9 - Liên kết và Quảng cáo
								</div>
							<div class='content'>
								Mọi thông tin liên quan về việc liên kết banner, link chữ... 
								trên website goldstar.com.vn xin liên hệ qua:
								Thông tin liên hệ Công Ty Cổ Phần GoldStar Việt Nam.
								</div>
							<div class='title'>
								10 - Phản hồi
								</div>
							<div class='content'>
								Chúng tôi hoan nghênh bất kỳ thông tin phản hồi, góp ý của người dùng muốn chúng tôi công bố trên website goldstar.com.vn.
								Nếu bạn có bất kỳ thắc mắc nào về điều khoản và điều kiện khi sử dụng goldstar.com.vn xin hãy liên hệ với chúng tôi theo:
								Thông tin liên hệ Công Ty Cổ Phần GoldStar Việt Nam
								</div>
							<div class='title'>
								11 -Các bạn có thể liên hệ với goldstar.com.vn 
									<a href='<?php echo SITE_URL?>/feedback/new' style='color: red;'>tại đây</a>
								</div>
		 				</div>
                </div>
			</div>
			<div class='col-md-5'>
				<?php echo $this->render('/widget/ho-tro-truc-tuyen.phtml');?>
				<div style="min-height: 10px;"></div>
				<div class='clearfix'></div>
				<div class='row'>
					<div class='col-md-12'>
						<div style="min-height: 10px;"></div>
						<div class='row'>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/new-videos.phtml');?>
								
								<?php echo $this->render('/widget/tin-nhanh.phtml');?>
							</div>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/tim-kiem.phtml');?>
								
								<?php echo $this->render('/widget/box-ho-tro.phtml');?>
								
								<?php echo $this->render('/widget/dich-vu.phtml');?>
							</div>
						</div>
						<div class='row'>
							<div class='col-md-12' style='padding: 0px;'>
								<?php //echo $this->render('/widget/chuyen-muc-hot.phtml');?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr>