<?php 
	$lu = Zend_Registry::get('user');
	$news = $this->news;
	$bestNews = $this->bestNews;
	$videos = $this->videos;
	$tinNhanh = $this->tinNhanh;
?>
<div style='min-height: 400px;'>
		<div class='row'>
			<div class='col-md-7'>
				<div id="content-main">
			    	<h1 title="Giá trị cốt lõi">Giá trị cốt lõi</h1>
                    	<h1>Con người</h1>
							<p>Con người là giá trị cốt lõi, là các giá trị bền vững làm nên thành công và tạo nên thương hiệu <strong>WEEKEND</strong>. Giá trị này được hình thành, xây dựng từ những kinh nghiệm thực tế &ndash; sự học hỏi và tôi luyện qua những thử thách trong suốt quá trình phát triển.</p>
							<p>Với Công ty con người là nguồn lực quý giá nhất. Do vậy, Công ty luôn tạo mọi điều kiện để các cá nhân phát huy hết tiềm năng của mình bằng cách khuyến khích sự học hỏi của cá nhân, đồng thời tin tưởng giao phó những trọng trách cao hơn, phù hợp với khả năng và kinh nghiệm mà cá nhân có thể đảm trách.</p>
							<h1>Phương pháp làm việc</h1>
							<p>Các công việc được thực hiện theo một quy trình chặt chẽ với mục tiêu chất lượng hàng đầu. Bằng&nbsp;việc ứng dụng quy trình phát triển sản phẩm và cung cấp dịch vụ cho khách hàng được tuân thủ chặt chẽ theo tiêu chuẩn. <strong>WEEKEND&nbsp;</strong>đã, đang và sẽ kiểm soát chặt chẽ chất lượng sản phẩm trước khi cung cấp ra thị trường.</p>
							<ul>
							<li>Làm việc tuân thủ quy trình.</li>
							<li>Làm việc theo đội.</li>
							<li>Trao đổi thông tin: <strong>WEEKEND&nbsp;</strong>có hệ thống lưu trữ, trao đổi thông tin giữa các bộ phận, cũng như trách nhiệm quản lý công việc rất rõ ràng.</li>
							</ul>
							<h1>Tính chuyên nghiệp và trách nhiệm</h1>
							<p>Tính chuyên nghiệp được <strong>WEEKEND&nbsp;</strong>thể hiện bằng việc cam kết cung cấp giải pháp và công cụ cho khách hàng với chất lượng cao, dịch vụ hậu mãi chu đáo và uy tín. Các CBNV khi giao tiếp với khách hàng bằng thái độ hòa nhã, lịch thiệp, tôn trọng nhau trong thương lượng và tranh luận để đi đến thống nhất. Hệ thống văn bản, biểu mẫu, tài liệu khi gửi đến khách hàng đã được công ty chuẩn hóa trong từng công đọan.</p>
							<p>Tính chuyên nghiệp trong <strong>WEEKEND&nbsp;</strong>được thể hiện bằng việc chấp hành nghiêm túc nguyên tắc quản lý điều hành, đảm bảo cho CBNV hoàn thành nhiệm vụ được giao. Với mỗi CBNV <strong>WEEKEND&nbsp;</strong>tính chuyên nghiệp còn thể hiện qua việc kiểm soát các cảm xúc cá nhân để lắng nghe, trao đổi nhằm giải quyết các rắc rối, khó khăn trong công việc theo mục tiêu chung của Công ty (Tuân thủ, thực hiện đúng các cam kết của công ty với khách hàng &ndash; đối tác).</p>
							<p>Với quan điểm sự thành công của Công ty được thể hiện qua việc thỏa mãn những quyền lợi hợp lý, đúng đắn của khách hàng và nhân viên. Do vậy trách nhiệm giữa TNC với khách hàng cũng như giữa <strong>WEEKEND&nbsp;</strong>với CBNV luôn được Ban lãnh đạo công ty quan tâm (thể hiện qua việc đưa ra các cam kết, chính sách của công ty trong từng thời kỳ). Với khách hàng CBNV công ty phải tôn trọng các cam kết của công ty, có trách nhiệm thực hiện đúng các công việc đã qui định, đồng thời trong quá trình thực hiện công việc luôn tuân tủ các quy tắc ứng xử chung là&nbsp;làm việc đúng giờ, đều đặn, hoàn thành công, đạt chất lượng cao và chấp hành nội qui, quy định và chuẩn mực đã đề ra.</p>
							<h1>Niềm tin vào chiến lược phát triển</h1>
							<p>Tin vào định hướng phát triển bền vững (bước từng bước vững chắc). Với quan điểm kế thừa để phát triển (không mang tính cách mạng), <strong>WEEKEND&nbsp;</strong>đã và sẽ có những đặc điểm và cách tiếp cận thị trường riêng của mình để phù hợp với xu thế phát triển chung của nền kinh tế Việt nam (Không chạy theo trào lưu).</p>
							<p>Tin tưởng khả năng sáng tạo và phát triển sản phẩm của con người trong <strong>WEEKEND&nbsp;</strong>. Các sản phẩm do <strong>WEEKEND&nbsp;</strong>tạo ra sẽ mang những đặc điểm, đặc tính kỹ thuật &ndash; nghiệp vụ riêng biệt của mình với một tiêu chí nhất định là đáp ứng nhu cầu khách hàng &ndash; nhu cầu thị trường (Khách hàng sẽ là thước đo chính xác nhất). Sản phẩm, dịch vụ của <strong>WEEKEND&nbsp;</strong>đã và sẽ phải là sản phẩm độc đáo có chất lượng.</p>
                </div>
			</div>
			<div class='col-md-5'>
				<?php echo $this->render('/widget/ho-tro-truc-tuyen.phtml');?>
				<div style="min-height: 10px;"></div>
				<div class='clearfix'></div>
				<div class='row'>
					<div class='col-md-12'>
						<div style="min-height: 10px;"></div>
						<div class='row'>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/new-videos.phtml');?>
								
								<?php echo $this->render('/widget/tin-nhanh.phtml');?>
							</div>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/tim-kiem.phtml');?>
								
								<?php echo $this->render('/widget/box-ho-tro.phtml');?>
								
								<?php echo $this->render('/widget/dich-vu.phtml');?>
							</div>
						</div>
						<div class='row'>
							<div class='col-md-12' style='padding: 0px;'>
								<?php //echo $this->render('/widget/chuyen-muc-hot.phtml');?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr>