<?php 
    $row = $this->row;
    $user = Zend_Registry::isRegistered('viewuser') ? Zend_Registry::get('viewuser') : array();
    $newCategorys = isset($this->newCategorys) ? $this->newCategorys : array();
    $hotCategorys = isset($this->hotCategorys) ? $this->hotCategorys : array();
    $this->url = '/category/manage-category'
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>
<?php echo $this->render('/widget/user_menu.phtml');?>
<div class="inner-page" style='margin-left: 15%; width: 85%;'>
	<div class="searchbar">
		<div class="search-left">
			<?php echo $this->render('/widget/search-box.phtml');?>
		</div>
		<div class="search-right">
			<p>Quản lý category</p>
		</div>
		<div class="clear"> </div>
	</div>
	
	<?php echo $this->render('/widget/manage-category-list.phtml');?>
	
	<div class="clear"> </div>
	<?php if($this->total > 0) :?>
        <?php echo $this->render("widget/vd-pagination.phtml");?>
    <?php endif;?>
</div>
<div class="clear"> </div>