<?php
   $form = $this->form;
?>
<div class="main row">
  <section class="twelve columns">
    <form method="post" class='cl_ajax' action="/feedback/new">
      <section class="module">
        <div class="module-body">
          <div id="account-billing-info">
          	<div class="limited-time" style='border-top: medium none;'>
		        <span class="no-counter">
		        	Cám ơn quý khách sử dụng sản phẩm của GoldStar, nhằm nâng cao chất lượng sản phẩm và

					dịch vụ của website kính mong quý khách hàng dành 5 phút để phản hồi lại cho chúng tôi cảm

					nhận khi sử dụng sản phẩm tại GoldStar</span>
		    </div>
				   
            <h1 class="section-title">Thông tin phản hồi</h1>

              <div id="feedback-new">
                <div class="row">
                  <div class="col-md-6">
                    <div>
                      <?php echo $form->uname;?>
                    </div>
              
                    <div>
                      <?php echo $form->umail;?>
                    </div>
              
                    <div>
                     <?php echo $form->uphone;?>
                    </div>
              
              		<div>
                     <?php echo $form->to;?>
                    </div>
                    
                  </div>
              
                  <div class="col-md-6">
                   <div>
                     <?php echo $form->title;?>
                    </div>
                    
                    <div>
                     <?php echo $form->content;?>
                    </div>
                    
                    <div>
                     <?php echo $form->more;?>
                    </div>
              
                    <input id="status" type="hidden" value="queued" name="status">
                  </div>
                </div>
              </div>
              
          </div>

          <div class="row complete-order-container">
          <?php echo $this->form->_cl_submit;?>
          </div>
        </div>
      </section>

    </form>
  </section>

</div>