<?php 
	$lu = Zend_Registry::get('user');
	$row = $this->row;
	$news = $this->news;
	$bestNews = $this->bestNews;
	$videos = $this->videos;
	$tinNhanh = $this->tinNhanh;
	$related = isset($this->related) ? $this->related : array();
?>
<div style='min-height: 400px;'>
		<div class='row'>
			<div class='col-md-7' style='padding-left: 0px; padding-right: 0px;'>
				<div id="content-main">
					<div class="video-inner videoview margin-left">
						<iframe width="100%" height="315" 
							src="//www.youtube.com/embed/<?php echo $row['ytid'];?>" 
							frameborder="0" allowfullscreen></iframe>
					</div>
					
					<?php $this->title = 'Sản phẩm mới';?>
				    <?php echo $this->render('/widget/tin-tuc-moi.phtml');?>
				</div>
			</div>
			<div class='col-md-5'>
				<?php echo $this->render('/widget/ho-tro-truc-tuyen.phtml');?>
				<div style="min-height: 10px;"></div>
				<div class='clearfix'></div>
				<div class='row'>
					<div class='col-md-12'>
						<div style="min-height: 10px;"></div>
						<div class='row'>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/new-videos.phtml');?>
								
								<?php echo $this->render('/widget/tin-nhanh.phtml');?>
							</div>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/box-ho-tro.phtml');?>
								
								<?php echo $this->render('/widget/dich-vu.phtml');?>
							</div>
						</div>
						<div class='row'>
							<div class='col-md-12' style='padding: 0px;'>
								<?php //echo $this->render('/widget/chuyen-muc-hot.phtml');?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr>