<div class='row'>
	<?php echo sand_dev_info_phtml(__FILE__);?>
	<?php $page = Zend_Registry::get('page');?>
	
	<?php if(has_perm('sudo')):?>
		<div class='col-md-12'>
		<?php echo $this->render('index/navbar.phtml');?>
		</div>
	<?php endif;?>
	<div class='col-md-6'>
		<?php if ($page == 'bill/index/new'):?>
		<h1> <?php echo 'Tạo hóa đơn mới';?></h1>
		<?php else:?>
		<h1> <?php echo 'Cập nhật hóa đơn';?></h1>
		<?php endif;?>
		<?php $this->form->setAttrib('class', 'cl_ajax');?>
		<?php echo $this->form;?>
	</div>
	<div class='col-md-6'>
	</div>
</div>