<div class="boxes">
    <div class="title-sidebar">Hỗ trợ</div> 
    <div class="boxes-content">
        <div>			<div class="textwidget"><h3>Hỗ trợ 24/7</h3>
		<p><span class="style1">ĐT : 0936.385.289 </span></p>
		<p><span class="style1"><strong>Yahoo</strong> : </span> <a href="ymsgr:sendIM?noidocoem_thienduonghanhphuc"> <img border="0" src="http://presence.msg.yahoo.com/online?u=noidocoem_thienduonghanhphuc&amp;m=g&amp;t=1&amp;l=us" alt=""> </a></p>
		<p><strong><span class="style1">Skype </span></strong></p>
		<script src="http://www.skypeassets.com/i/scom/js/skype-uri.js" type="text/javascript"></script>
		<div id="SkypeButton_Chat_lamdinhmy_1">
		<script type="text/javascript">// &lt;![CDATA[
		Skype.ui({
		      "name": "chat",
		      "element": "SkypeButton_Chat_lamdinhmy_1",
		      "participants": ["lamdinhmy"],
		      "imageSize": 15
		    });
		// ]]&gt;</script><p id="SkypeButton_Chat_lamdinhmy_1_paraElement" style="font-size:14px; color:#444444"><a href="skype:lamdinhmy?chat" onclick="Skype.tryAnalyzeSkypeUri('chat', '0');"><img src="http://www.skypeassets.com/i/scom/images/skype-buttons/chatbutton_16px.png" alt="Skype chat, instant message" role="Button" style="border:0; margin:16px; vertical-align:-20px;"></a></p>
		</div></div>
		</div>        
    </div>
</div>