<div class='top-news'>
	<div class='heading'>
		Chuyên mục hot
		<i class='glyphicon glyphicon-chevron-down pull-right'
		style='font-size: 16px;'></i>
	</div>
	<div class='separator'></div>
	<!-- Nav tabs -->
	<ul class="nav nav-tabs" role="tablist">
	  <li class="active"><a href="#hot_tab_video" role="tab" data-toggle="tab">Video</a></li>
	  <li>
	  	<a href="#hot_tab_product" role="tab" data-toggle="tab">Sản phẩm</a></li>
	  <li><a href="#hot_tab_new" role="tab" data-toggle="tab">Tin</a></li>
	</ul>
	
	<!-- Tab panes -->
	<div class="tab-content">
	  <div class="tab-pane active" id="hot_tab_video">
	  		<div class="video1">
			  <a href="#">
				  <div class="thumb">
					<img title="Cô Gái Mở Đường - LEG Official" src="http://img.youtube.com/vi/U7V--PQreqo/0.jpg">
						<div class="duration">
														00:03:41						</div>
					</div>
				<div class="info">
						<span class="name_video">
													Cô Gái Mở Đường - LEG Official											</span>
						<span class='view_video'><i class='glyphicon glyphicon-eye'></i> 359</span>
				</div>
				<div class="clear"> </div>
			   	</a>
			</div>
		
			<div class="video1">
			  <a href="#">
				  <div class="thumb">
					<img title="Mình yêu nhau đi - phiên bản cô giáo TIẾNG ANH (X-Team)" src="http://img.youtube.com/vi/pswOI-HmVws/0.jpg">
						<div class="duration">
														00:02:49						</div>
					</div>
				<div class="info">
					<span class="name_video">
													Mình yêu nhau đi - phiên bản cô giáo TIẾNG ANH .....											</span>
						<span class='view_video'><i class='glyphicon glyphicon-eye'></i> 359</span>
				</div>
				<div class="clear"> </div>
			   	</a>
			</div>
			
			<div class="video1">
			  <a href="#">
				  <div class="thumb">
					<img title="Như Hexi - Mình yêu nhau đi - Cover Bựa" src="http://img.youtube.com/vi/sxElEUzoKBQ/0.jpg">
						<div class="duration">
														00:03:38						</div>
					</div>
				<div class="info">
					<span class="name_video">
													Như Hexi - Mình yêu nhau đi - Cover Bựa											</span>
						   <span class='view_video'><i class='glyphicon glyphicon-eye'></i> 359</span>
				</div>
				<div class="clear"> </div>
			   	</a>
			</div>
			
			<div class="video1">
			  <a href="#">
				  <div class="thumb">
					<img title="Mình Yêu Nhau Đi Thái Tuyết Trâm Cover Hot" src="http://img.youtube.com/vi/ndFSzoUkb60/0.jpg">
						<div class="duration">
														00:03:05						</div>
					</div>
				<div class="info">
					<span class="name_video">
													Mình Yêu Nhau Đi Thái Tuyết Trâm Cover Hot .....											</span>
				 	  <span class='view_video'><i class='glyphicon glyphicon-eye'></i> 359</span>	
				</div>
				<div class="clear"> </div>
			   	</a>
			</div>
			
			<div class="video1">
			  <a href="#">
				  <div class="thumb">
					<img title="[Cover] Mình yêu nhau đi - Hương Ly ft Quỳnh Anh" src="http://img.youtube.com/vi/-HoaXwJQA-0/0.jpg">
						<div class="duration">
														00:03:22						</div>
					</div>
				<div class="info">
					<span class="name_video">
													[Cover] Mình yêu nhau đi - Hương Ly ft Quỳnh A .....											</span>

						<span class='view_video'><i class='glyphicon glyphicon-eye'></i> 359</span>										    	
				</div>
				<div class="clear"> </div>
			   	</a>
			</div>
	  	</div>
	  <div class="tab-pane" id="hot_tab_product">
			<div class='new-list'>
				<div class='item'>
					<div class='row'>
						<div class='col-md-4'>
							<img 
								alt="Banks warned about exchange rate dangers in 2009" 
								src="http://joomlatemplates.youjoomla.info/dailynews/media/k2/items/cache/184b7cb84d7b456c96a0bdfbbeaa5f14_L.jpg" width="100%">
						</div>
						<div class='col-md-8'>
							<span> Banks warned about exchange rate dangers in 2009 </span></br>
							<span> 24<br><b> October</b>  </span></br>
						</div>
					</div>
				</div>
				
				<div class='item'>
					<div class='row'>
						<div class='col-md-4'>
							<img 
								alt="Banks warned about exchange rate dangers in 2009" 
								src="http://joomlatemplates.youjoomla.info/dailynews/media/k2/items/cache/184b7cb84d7b456c96a0bdfbbeaa5f14_L.jpg" width="100%">
						</div>
						<div class='col-md-8'>
							<span> Banks warned about exchange rate dangers in 2009 </span></br>
							<span> 24<br><b> October</b>  </span></br>
						</div>
					</div>
				</div>
				
				<div class='item'>
					<div class='row'>
						<div class='col-md-4'>
							<img alt="Putin frees his enemies as part of Sochi spin" 
								src="http://joomlatemplates.youjoomla.info/dailynews/media/k2/items/cache/e0a70f72bdae9885bfc32d7cd19a26a1_L.jpg" width="100%">
						</div>
						<div class='col-md-8'>
							<span> Banks warned about exchange rate dangers in 2009 </span></br>
							<span> 24<br><b> October</b>  </span></br>
						</div>
					</div>
				</div>
				
				<div class='item'>
					<div class='row'>
						<div class='col-md-4'>
							<img 
								alt="Banks warned about exchange rate dangers in 2009" 
								src="http://joomlatemplates.youjoomla.info/dailynews/media/k2/items/cache/2ff2ba0051687eef5ca0459cf942940c_L.jpg" width="100%">
						</div>
						<div class='col-md-8'>
							<span> Banks warned about exchange rate dangers in 2009 </span></br>
							<span> 24<br><b> October</b>  </span></br>
						</div>
					</div>
				</div>
				
				<div class='item'>
					<div class='row'>
						<div class='col-md-4'>
							<img 
								alt="Banks warned about exchange rate dangers in 2009" 
								src="http://joomlatemplates.youjoomla.info/dailynews/media/k2/items/cache/ffee2447b152494b43d9816faaea83c8_L.jpg" width="100%">
						</div>
						<div class='col-md-8'>
							<span> Banks warned about exchange rate dangers in 2009 </span></br>
							<span> 24<br><b> October</b>  </span></br>
						</div>
					</div>
				</div>
			</div>
		</div>
	  <div class="tab-pane" id="hot_tab_new">
			<ul class='new-list'>
				<li class='item'>
					<a href="#">
						<span class="title">
							Công văn số 9456/TCHQ-QLRR ngày 29/7/2014 của Tổng cục 
								Hải quan v/v áp dụng bộ tiêu chí theo Quyết định 279/QĐ-BTC 
						</span>
					</a>
				</li>
				<li class='item'>
					<a href="#">
						<span class="title">
							Công văn số 9509/TCHQ-KTSTQ ngày 29/7/2014 của Tổng cục Hải quan v/v 
								trả lời Công văn 1606/2014/CV-ABTEL về việc yêu cầu tạm đình 
									chỉ việc thi hành quyết định hành chính  
						</span>
					</a>
				</li>
				<li class='item'>
					<a href="#">
						<span class="title">
							Công văn số 9504/TCHQ-TXNK ngày 29/7/2014 của Tổng cục Hải quan v/v xử lý 
								nợ thuế về việc xem xét dừng áp
								 dụng biện pháp cưỡng chế và xóa phạt chậm nộp (8/8/2014)
						</span>
					</a>
				</li>
				<li class='item'>
					<a href="#">
						<span class="title">
							Công văn số 9502/TCHQ-GSQL ngày 29/7/2014 của Tổng cục Hải quan v/v 
								hàng hóa xuất khẩu qua cửa khẩu phụ nằm ngoài khu Kinh tế cửa khẩu (
						</span>
					</a>
				</li>
				<li class='item'>
					<a href="#">
						<span class="title">
							Công văn số 9515/TCHQ-VNACCS ngày 29/7/2014 của Tổng cục Hải quan v/v
								 số lượng số thập phân của trị giá và đơn vị hàng hóa nhập khẩu 
						</span>
					</a>
				</li>
				<li class='item'>
					<a href="#">
						<span class="title">
							Công văn số 2888/TCT-CS ngày 29/7/2014 của Tổng cục Thuế v/v 
								chính sách thuế Thu nhập doanh nghiệp 
						</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
</div>