<?php 
		//Lay tin dich vu
    	$dich_vu_iid = get_conf('dich_vu_iid','37');
    	$where = array('parent_category_iid' => $dich_vu_iid);
    	//$where = array();
    	$cond['where'] = $where;
    	$cond['limit'] = 5;
    	$cond['ts'] = -1;
    	$r = Dao_Node_New::getInstance()->findAll($cond);
    	if($r['success']){
    		$dichvu = $r['result'];
    	}
?>
<?php if(count($dichvu) > 0):?>
<div class="boxes">
	<div class="title-sidebar">Dịch vụ</div>
	<div class="boxes-content">
		<div class="boxes-content">
			<ul class="news-flash">
				<?php foreach ($dichvu as $new):?>
		            <li>
            			<a title="<?php echo $new['name'];?>" 
            				href="<?php echo node_link('new', $new);?>">
			            	<img align="middle" 
			            		width='64px'
			            		height='46px'
			            		alt="<?php echo $new['name'];?>" 
			            		src="<?php echo $new['avatar'];?>">            
			            			<?php echo $new['name'];?></a>
		            <div class="clearfix"></div> 
		            </li>
				<?php endforeach;?>
        	</ul>
		</div>
	</div>
</div>
<?php endif;?>