<?php 
	$dichvu = isset($this->dichvu) ? $this->dichvu : array();
?>
<?php if(count($dichvu) > 0):?>
<div class="boxes">
	<div class="title-sidebar">Dịch vụ</div>
	<div class="boxes-content">
		<div class="boxes-content">
			<ul class="news-flash">
				<?php foreach ($dichvu as $new):?>
		            <li>
		            	<img align="middle" 
		            		width='64px'
		            		height='46px'
		            		alt="<?php echo $new['name'];?>" 
		            		src="<?php echo $new['avatar'];?>">            
	            			<a title="<?php echo $new['name'];?>" 
	            				href="<?php echo node_link('new', $new);?>">
		            			<?php echo $new['name'];?></a>
		            <div class="clearfix"></div> 
		            </li>
				<?php endforeach;?>
        	</ul>
		</div>
	</div>
</div>
<?php endif;?>