<div class="boxes">
	    <div class="title-sidebar">Dịch vụ</div>
	    <div class="boxes-content">
	        <div class="boxes-content">
		        <ul class="news-flash">
		            <li><img align="middle" alt="Quyết toán thuế" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/thue.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">            <a title="Quyết toán thuế" href="http://hangngay.com.vn/service/quyet-toan-thue/">Quyết toán thuế</a>
		            <div class="clearfix"></div> 
		                </li><li><img align="middle" alt="Kê khai thuế hàng tháng" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/ke-khai-thue.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">            <a title="Kê khai thuế hàng tháng" href="http://hangngay.com.vn/service/ke-khai-thue-hang-thang/">Kê khai thuế hàng tháng</a>
		            <div class="clearfix"></div> 
		                </li><li><img align="middle" alt="Kế toán thuế trọn gói" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/dich-vu-ke-toan-thue.png&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">            <a title="Kế toán thuế trọn gói" href="http://hangngay.com.vn/service/ke-toan-thue-tron-goi/">Kế toán thuế trọn gói</a>
		            <div class="clearfix"></div> 
		                </li><li><img align="middle" alt="Kế toán chuyên nghiệp &ndash; tư vấn miễn phí" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/tuvanketoan.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">            <a title="Kế toán chuyên nghiệp &ndash; tư vấn miễn phí" href="http://hangngay.com.vn/service/ke-toan-chuyen-nghiep-tu-van-mien-phi/">Kế toán chuyên nghiệp &ndash; tư vấn miễn phí</a>
		            <div class="clearfix"></div> 
		                </li>        
                </ul>
		    </div>
	    </div>
	</div>