<div class='row'>
	<div class='col-md-12' style='padding-left: 0px;'>
			<div class="checkdomain pnlsupportonline">
                <h4 class="titleside titlesupportonline">
                	<i class='glyphicon glyphicon-comments' style="color: #29739d;"></i> Hỗ trợ trực tuyến</h4>
                <a href="javascript:openonline()">
                    <img src="<?php echo ASSETS_CDN?>/images/support-online1.jpg" alt="goldstarsoft" style="border: 0">
                </a>
            </div>
		</div>
</div>