<?php 
	$videos = isset($this->videos) ? $this->videos : array();
?>
<?php if(count($videos) > 0):?>
<div class="boxes">
	<div class="title-sidebar">Video hướng dẫn</div>
	<div class="boxes-content">
		<div class="boxes-content">
			<?php foreach ($videos as $video):?>
	            	<?php $avatar = "http://img.youtube.com/vi/{$video['ytid']}/0.jpg";?>
					<div class="video1">
					  <a href="<?php echo node_link('video', $video);?>">
						  <div class="thumb">
							<img src="<?php echo $avatar;?>" 
								title="<?php echo $video['name'];?>" />
								<div class="duration">
									<?php $video['duration'] = isset($video['duration']) ? $video['duration'] : 0;?>
									<?php echo gmdate("H:i:s", (int)$video['duration']);?>
								</div>
							</div>
						<div class='info'>
							<span>
								<?php if(strlen($video['name']) > 46):?>
									<?php echo char_breadcumb($video['name'], 46) . ' .....';?>
								<?php else:?>
									<?php echo $video['name'];?>
								<?php endif;?>
							</span>
						</div>
						<div class="clear"> </div>
					   	</a>
					</div>
					<div style='border-bottom: 1px dashed #D5D5D5;'></div>
			<?php endforeach;?>
		</div>
	</div>
</div>
<?php endif;?>