<?php 
	$tinNhanh = isset($this->tinNhanh) ? $this->tinNhanh : array();
?>
<?php if(count($tinNhanh) > 0) :?>
	<div class="boxes">
	    <div class="title-sidebar">Tin nhanh</div>
	    <div class="boxes-content">
	        <ul class="news-flash">
	        	<?php foreach ($tinNhanh as $new):?>
	        	    <li>
	        	    	<img align="middle"
	        	    		width='62px'
	        	    		height='42px' 
	        	    		alt="<?php echo $new['name']?>" 
        	    			src="<?php echo $new['avatar'];?>">                
        	    			<a title="<?php echo $new['name'];?>" 
        	    				href="<?php echo node_link('new', $new);?>">
	        	    			<?php echo $new['name'];?></a>
	                	<div class="clearfix"></div> 
	                </li>
                <?php endforeach;?>
		    </ul>
	    </div>
	</div>
<?php endif;?>