<div class="boxes">
    <div class="title-sidebar">Tin nhanh</div>
    <div class="boxes-content">
        <ul class="news-flash">
            <li><img align="middle" alt="Bạn nên làm gì với lương của mình?" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/giam-thue-tndn-doi-voi-dn-co-tong-doanh-thu-duoi-20-ty-dongnam.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Bạn nên làm gì với lương của mình?" href="http://hangngay.com.vn/ban-nen-lam-gi-voi-luong-cua-minh/">Bạn nên làm gì với lương của mình?</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Người thành công làm gì sau giờ làm việc?" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/11/00-49733.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Người thành công làm gì sau giờ làm việc?" href="http://hangngay.com.vn/nguoi-thanh-cong-lam-gi-sau-gio-lam-viec/">Người thành công làm gì sau giờ làm việc?</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Làm thế nào để “cứu” laptop khi bị nước vào?" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/11/nuoc-vao-may.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Làm thế nào để “cứu” laptop khi bị nước vào?" href="http://hangngay.com.vn/lam-the-nao-de-cuu-laptop-khi-bi-nuoc-vao/">Làm thế nào để “cứu” laptop khi bị nước vào?</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Tại sao nói :Lựa chọn một phần mềm &ndash; tức là lựa chọn một giải pháp!" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/cp.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Tại sao nói :Lựa chọn một phần mềm &ndash; tức là lựa chọn một giải pháp!" href="http://hangngay.com.vn/tai-sao-noi-lua-chon-mot-phan-mem-tuc-la-lua-chon-mot-giai-phap/">Tại sao nói :Lựa chọn một phần mềm &ndash; tức là lựa chọn một giải pháp!</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Tổng giá trị đầu tư phần mềm là bao nhiêu? để hợp lý ?" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/slide22.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Tổng giá trị đầu tư phần mềm là bao nhiêu? để hợp lý ?" href="http://hangngay.com.vn/tong-gia-tri-dau-tu-phan-mem-la-bao-nhieu-de-hop-ly/">Tổng giá trị đầu tư phần mềm là bao nhiêu? để hợp lý ?</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Có nên đóng: Chi phí bảo trì phần mềm kế toán ?" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/giam-thue-tndn-doi-voi-dn-co-tong-doanh-thu-duoi-20-ty-dongnam.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Có nên đóng: Chi phí bảo trì phần mềm kế toán ?" href="http://hangngay.com.vn/co-nen-dong-chi-phi-bao-tri-phan-mem-ke-toan/">Có nên đóng: Chi phí bảo trì phần mềm kế toán ?</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="WEBSITE TRA CỨU THÔNG TIN HÓA ĐƠN HỢP PHÁP" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/10/dich-vu-ke-toan-thue.png&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="WEBSITE TRA CỨU THÔNG TIN HÓA ĐƠN HỢP PHÁP" href="http://hangngay.com.vn/website-tra-cuu-thong-tin-hoa-don-hop-phap/">WEBSITE TRA CỨU THÔNG TIN HÓA ĐƠN HỢP PHÁP</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Hướng dẫn cách khai và nộp thuế" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/11/anhHoidap.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Hướng dẫn cách khai và nộp thuế" href="http://hangngay.com.vn/huong-dan-cach-khai-va-nop-thue/">Hướng dẫn cách khai và nộp thuế</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Phát hiện chip gián điệp trong hàng loạt bàn là, ấm nước Trung Quốc" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/11/gian-diep.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Phát hiện chip gián điệp trong hàng loạt bàn là, ấm nước Trung Quốc" href="http://hangngay.com.vn/phat-hien-chip-gian-diep-trong-hang-loat-ban-la-am-nuoc-trung-quoc/">Phát hiện chip gián điệp trong hàng loạt bàn là, ấm nước Trung Quốc</a>
                <div class="clearfix"></div> 

                </li><li><img align="middle" alt="Điện toán đám mây: cũ người, mới ta" src="http://hangngay.com.vn/wp-content/themes/goldstar/timthumb.php?src=http://hangngay.com.vn/wp-content/uploads/2013/11/1383239721-cloud-1.jpg&amp;h=40&amp;w=60&amp;q=100&amp;zc=1">                <a title="Điện toán đám mây: cũ người, mới ta" href="http://hangngay.com.vn/dien-toan-dam-may-cu-nguoi-moi-ta/">Điện toán đám mây: cũ người, mới ta</a>
                <div class="clearfix"></div> 

                </li>        </ul>
    </div>
</div>