<?php 
	$news = $this->news;
	$title = $this->title;
	$is_home_page = isset($this->is_home_page) ? true : false;
?>
<?php if(count($news) > 0):?>
<div class='col-md-12'>
	<div class='row heading'>
		<h3 style="margin-top: 0;">
		<i class='glyphicon glyphicon-home'></i>
		<?php echo $title;?></h3>
	</div>
	<?php foreach ($news as $new):?>
	<div class="row">
    	<div class="col-md-12 title_news">
    	   <a href="<?php echo node_link('new', $new);?>" class="txt_link"><?php echo $new['name'];?></a>
	    </div>
    	<div class="col-md-12">
			<div class='col-md-3' style='padding-left: 0px; padding-right:0px;'>
				<a href="<?php echo node_link('new', $new);?>" title="<?php echo $new['name'];?>">
			       <img class="img-responsive img-thumbnail" src="<?php echo $new['avatar'];?>">
			    </a>
			</div>
			<div class='col-md-9'>
				<div class="text-content">
			        <div style="text-align: justify;">
				        <p class="news_desc"><?php echo _wordwrap($new['description']);?></p>
			        </div>
		        </div>
			</div>
    	</div>
	</div>
	<hr>
	<?php endforeach;?>
	<?php if($is_home_page):?>
		<div class='pull-right'>
			<a href='/new/tin-moi'>
				<i class='glyphicon glyphicon-chevron-right' 
					style='color: green; text-decoration: none !important;'></i>
				Xem tất cả
			</a>
		</div>
	<?php else:?>
		<?php if($this->total > 0) :?>
	        <?php echo $this->render("widget/gold-pagination.phtml");?>
	    <?php endif;?>
	<?php endif;?>
</div>
<?php else:?>
<div class="no-news">
    <div class='heading'>
		<h3 style="margin-top: 0;">
		<i class='glyphicon glyphicon-home'></i>
		<?php echo $title;?></h3>
	</div>
	<div class="clear-fix clear"></div>
	<div class="alert alert-info" role="alert">Chưa có bài đăng nào trong chuyên mục này.</div>
</div>
<?php endif;?>