<?php $sso = array('google', 'facebook');?>
<div class="col-md-12">
    <div class="clearfix clear"></div>
	<div class="well login-container">
        	<div class="login-provider">
        		<h3>Đăng nhập bằng</h3>
        		<?php foreach($sso as $s) :?>
        		<div class="img-container btn">
        			<a href="/user/oauth?login=<?php echo $s?>">
	    				<img width="20" height="20" src="<?php echo ASSETS_CDN?>/images/sso/<?php echo $s;?>.png" alt="<?php echo $s;?>">
	    			</a>
        		</div>
        		<div class="clearfix clear" style="margin: 5px 0;"></div>
        		<?php endforeach;?>
        	</div>
        	<div class="vertical-separator">
        		<span class="separator-text">HOẶC</span>
        	</div>
        	<div class="loginForm">
	        	<div id='login_form'>
		        	<h2>Thông tin đăng nhập</h3>
		        	<?php 
	        	    $form = new User_Form_Login();
	                $form->build();
	                $form->setAction('/user/login')
	                    ->setAttrib('class', 'cl_ajax');
	                $form->getElement('_cl_submit')->setAttrib('class', 'btn-primary btn btn-large');
	                echo $form;
	        	?>
	        	<div class="clearfix clear"></div>
	        	<div Quên mật khẩu? <a href="/user/forgot-password" id='remind_password'>Nhận mật khẩu mới qua email</a></div>
        	</div>
        	
        	<div id='remind_password_form' style='display:none'>
    		<h3>Thiết lập lại mật khẩu</h3>
        	<b><a href='/user/login' id='login'>Đăng nhập</a></b>
        	<?php 
        	    $form = new User_Form_RemindPassword();
                $form->build();
                $form->setAction('/user/forgot-password')
                    ->setAttrib('class', 'cl_ajax')
                    ->setAttrib('data-sand-callbacks', 'remind_pass_success')
                	->setAttrib('data-sand-callbacks', 'remind_pass_error');
                echo $form;
        	?>        	
        	</div>
        </div>
  </div>
</div>
<?php $this->inlineScript()->captureStart();?>
	$(document).ready(function(){
	
	    $("#login").click(function(e){
	    	e.preventDefault();
	    	$("#login_form").show();
	    	$("#remind_password_form").hide();
	    });
	   
	    $("#remind_password").click(function(e){
	    	e.preventDefault();
	    	$("#login_form").hide();
	    	$("#remind_password_form").show();
	    });
	});
<?php $this->inlineScript()->captureEnd();?>
