<?php $lu = Zend_Registry::get('user');?>
<?php 
	$list = isset($this->list) ? $this->list : array();
 	$tag = isset($this->tag) ? $this->tag : array();
 	$newNews = isset($this->newNews) ? $this->newNews : array();
 	$hotNews = isset($this->hotNews) ? $this->hotNews : array();
?>
<div class="left-content">
	<div class="searchbar">
		<div class="search-left">
			<p><?php echo $tag['name'] ?> - Những bản cover hay nhất</p>
		</div>
		<div class="search-right">
			<form>
				<input type="text"><input type="submit" value="" />
			</form>
		</div>
		<div class="clear"> </div>
	</div>
	<div class="box">
	<?php if(count($list) > 0):?>
		<div class="grids">
		<?php $k = 0;?>
		<?php foreach ($list as $new):?>
			<?php if($k % 3 == 0 && $k > 0):?>
				</div>
				<div class="clear"> </div>
				<div class="grids">
			<?php endif;?>
				<?php $imgLink = "http://img.youtube.com/vi/{$new['ytid']}/0.jpg";?>
				<div class="grid" style='margin-bottom: 4px;'>
					<a href="<?php echo node_link('new', $new);?>"><h3>
						<?php echo $new['name'];?></h3></a>
					<a href="<?php echo node_link('new', $new);?>">
						<img src="<?php echo $imgLink;?>" title="new-name"
						style='width: 243px;height: 152px;'>
						<img class="tidypics-photo-start" width="35px" height="25px" 
							src="<?php echo ASSETS_CDN?>/img/play_youtube.png" 
							style="left: 102px; position: absolute; top: 116px; width: 50px; 
							height: 40px; cursor: pointer;">
						</a>
					<div class="time">
						<?php $new['duration'] = isset($new['duration']) ? $new['duration'] : 0;?>
						<span><?php echo gmdate("H:i:s", (int)$new['duration']);?></span>
					</div>
					<div class="grid-info">
						<div class="new-share">
							<ul>
								<li><a href="#"><img src="<?php echo ASSETS_CDN?>/img/likes.png" title="links"></a></li>
								<li><a href="#"><img src="<?php echo ASSETS_CDN?>/img/link.png" title="Link"></a></li>
								<li><a href="#"><img src="<?php echo ASSETS_CDN?>/img/views.png" title="Views"></a></li>
							</ul>
						</div>
						<div class="new-watch">
							<a href="<?php echo node_link('new', $new);?>">Xem ngay</a>
						</div>
						<div class="clear"> </div>
						<div class="lables">
							<p>By:<a href="#"><?php echo $new['u']['name'];?></a></p>
						</div>
					</div>
				</div>
			<?php $k ++;?>
		<?php endforeach;?>
		</div>
	<?php endif;?>
	<div class="clear"> </div>
</div>
	<div class="clear"> </div>
	<ul class="dc_pagination dc_paginationA dc_paginationA03">
	  <li><a href="#" class="first">First</a></li>
	  <li><a href="#" class="previous">Previous</a></li>
	  <li><a href="#">1</a></li>
	  <li><a href="#">2</a></li>
	  <li><a href="#" class="current">3</a></li>
	  <li><a href="#">4</a></li>
	  <li><a href="#">5</a></li>
	  <li><a href="#" class="next">Next</a></li>
	  <li><a href="#" class="last">Last</a></li>
	  
	</ul>
	<div class="clear"> </div>
</div>
<div class="right-content">
	<?php echo $this->render('/new/hot-news.phtml');?>
<div class="clear"> </div>
	<?php echo $this->render('/new/new-news.phtml');?>
</div>
<div class="clear"> </div>
