<?php 
	$lu = Zend_Registry::get('user');
?>
<div style='min-height: 400px;'>
		<div class='row'>
			<div class='col-md-7'>
				<div class='separator-high'></div>
				<?php $this->title = 'Tin mới';?>
				<?php $this->url = '/new/tin-moi'?>
				<?php echo $this->render('/widget/tin-tuc-moi.phtml');?>
			</div>
			<div class='col-md-5'>
				<?php echo $this->render('/widget/ho-tro-truc-tuyen.phtml');?>
				<div style="min-height: 10px;"></div>
				<div class='clearfix'></div>
				<div class='row'>
					<div class='col-md-12'>
						<div style="min-height: 10px;"></div>
						<div class='row'>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/tin-nhanh.phtml');?>
								
								<?php echo $this->render('/widget/new-videos.phtml');?>
							</div>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/box-ho-tro.phtml');?>
								
								<?php echo $this->render('/widget/dich-vu.phtml');?>
							</div>
						</div>
						<div class='row'>
							<div class='col-md-12' style='padding: 0px;'>
								<?php //echo $this->render('/widget/chuyen-muc-hot.phtml');?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr>