<?php 
	$lu = Zend_Registry::get('user');
	$row = $this->row;
	$news = $this->news;
	$bestNews = $this->bestNews;
	$videos = $this->videos;
	$tinNhanh = $this->tinNhanh;
?>
<div style='min-height: 400px;'>
		<div class='row'>
			<div class='col-md-7'>
				<div id="content-main">
					<h2><?php echo $row['name'];?></h2>
					<?php echo $row['content'];?>
					
					<div class='pull-right'>
						<b><?php echo $row['author'];?></b><br>
						Nguồn: <span><?php echo $row['source'];?></span>
					</div>
				</div>
			</div>
			<div class='col-md-5'>
				<?php echo $this->render('/widget/ho-tro-truc-tuyen.phtml');?>
				<div style="min-height: 10px;"></div>
				<div class='clearfix'></div>
				<div class='row'>
					<div class='col-md-12'>
						<div style="min-height: 10px;"></div>
						<div class='row'>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/tin-nhanh.phtml');?>
							</div>
							<div class='col-md-6' style='padding: 0px'>
								<?php echo $this->render('/widget/box-ho-tro.phtml');?>
								
								<?php echo $this->render('/widget/dich-vu.phtml');?>
							</div>
						</div>
						<div class='row'>
							<div class='col-md-12' style='padding: 0px;'>
								<?php echo $this->render('/widget/chuyen-muc-hot.phtml');?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<hr>