<div id='footer' class='fixed-bottom hidden-print promo-wrapper' >
	<div class='row' style=' margin: 0 auto; width: 990px;'>
		<div class='col-md-6'>
			<div class="column-footer fl">
				<!--<div class="top fl"><a href=""><img src="http://sis.vn/sis-ieos.nsf/ImagesSis2012/$File/RSS.jpg" /> RSS</a></div>
				<div class="top fl"><a href="mailto:sales@sisvn.com"><img src="http://sis.vn/sis-ieos.nsf/ImagesSis2012/$File/email.jpg" /> Email</a></div>
				<div class="top fl"><a href=""><img src="http://sis.vn/sis-ieos.nsf/ImagesSis2012/$File/feeback.jpg" /> Thông tin phản hồi</a></div>-->
				<div style="height:15px;" class="cl"></div>
				<div class="information-footer fl" style='line-height: 30px;'>
					<div class=''>Cơ quan chủ quản: <span class="bold" itemprop="name">Công ty Cổ phần Goldstar &ndash; GoldstarJSC</span></div>
					<div class="">Địa chỉ: 110 Trần Phú, Hà Đông - Hà Nội</div>
					<div class="">Điện thoại: 043 555 8655 (043.555 8656) - Fax: 043 772 3520</div>
					<div style="height:3px;" class="cl"></div>
				</div>
			</div>
		</div>
		<div class='col-md-6'>
			<div class="column-footer fr">
				<div class="top bold fr"><a href="/site/dieu-khoan">Điều khoản</a></div>
				<div class="top bold fr"><a href="/feedback/new">Liên hệ</a></div>
				<div class="clearfix"></div>
				<!-- 
				<img class="fr" src="" width='50px' height='50px'>
				 -->
			 	<div>Email: lienhe@goldstar.com.vn</div>
				<div class="top fr">Copyright &copy; Goldstar.com.vn</div>
				<div class="cl"></div>
			</div>
		</div>
	</div>
	
</div> 