<div id='footer' class='fixed-bottom hidden-print promo-wrapper' >
	<div class='row' style=' margin: 0 auto; width: 990px;'>
		<div class='col-md-6'>
			<div class="column-footer fl">
				<!--<div class="top fl"><a href=""><img src="http://sis.vn/sis-ieos.nsf/ImagesSis2012/$File/RSS.jpg" /> RSS</a></div>
				<div class="top fl"><a href="mailto:sales@sisvn.com"><img src="http://sis.vn/sis-ieos.nsf/ImagesSis2012/$File/email.jpg" /> Email</a></div>
				<div class="top fl"><a href=""><img src="http://sis.vn/sis-ieos.nsf/ImagesSis2012/$File/feeback.jpg" /> Thông tin phản hồi</a></div>-->
				<div style="height:15px;" class="cl"></div>
				<div class="information-footer fl">
				<div>Cơ quan chủ quản: <span class="bold" itemprop="name">Công ty Cổ phần Goldstar &ndash; GoldstarJSC</span></div>
				<div>Địa chỉ: 110 Trần Phú, Hà Đông - Hà Nội</div>
				<div>Điện thoại: 043 555 8655 (043.555 8656) - Fax: 043 772 3520</div>
				<div>Email: lienhe@goldstar.com.vn</div>
			<div style="height:3px;" class="cl"></div>
			<div> 
			<!-- GoStats Simple HTML Based Code -->
			<!--<a target="_blank" title="Bộ đếm web cho blog miễn phí" href="http://gostats.vn"><img alt="Bộ đếm web cho blog miễn phí" 
			src="http://c2.gostats.vn/bin/count/a_648340/t_7/i_3/z_0/show_visitors/counter.png" 
			style="border-width:0" /></a>-->
			<!--<a target="_blank" title="Các bộ đếm & Phân tích lưu lượng" href="http://gostats.vn"><img alt="Các bộ đếm & Phân tích lưu lượng" 
			src="http://c2.gostats.vn/bin/count/a_648340/t_3/i_5/counter.png" 
			style="border-width:0" /></a>-->
			<!-- End GoStats Simple HTML Based Code -->
			<!--<a href="http://www.alexa.com/siteinfo/http://sis.vn/"><script type='text/javascript' src='http://xslt.alexa.com/site_stats/js/s/c?url=http://sis.vn/'></script></a>-->
			</div>
				</div>
			</div>
		</div>
		<div class='col-md-6'>
			<div class="column-footer fr">
				<div class="top bold fr"><a href="/site/dieu-khoan">Điều khoản</a></div>
				<div class="top bold fr"><a href="#">HotLine</a></div>
				<div class="top bold fr"><a href="#">Tuyển dụng</a></div>
				<div class="top bold fr"><a href="/site/lien-he">Liên hệ</a></div>
				<div class="clearfix"></div>
				<!-- 
				<img class="fr" src="" width='50px' height='50px'>
				 -->
				<div class="top fr">Copyright &copy; Goldstar.com.vn</div>
				<div class="cl"></div>
			</div>
		</div>
	</div>
	
</div> 