<?php 
    $lu =  Zend_Registry::get('user');
    $page = 'home';
    if (isset($_REQUEST['page']))
        $page = $_REQUEST['page'];
    if (Zend_Registry::isRegistered('page'))
        $page = Zend_Registry::get('page');

?>
<div class="navbar" id='user_menu'>
         <div class="navbar-header">
	        </div>
	        <div class="navbar-collapse collapse" style='padding: 0;'>
	          <div id='top-menu'>
	          	<a href="http://gss.local/" style='text-decoration:none;font-size: 14px;'>
	          		<span class='header-log'>GoldStar</span>.com.vn
	          		<!-- 
					<img class="logo-top fl" 
						src="http://gss.local/images/logo-top.jpg" width="196px;" height="52px;" itemprop="url">
	          		 -->
					</a>
          	<ul class='nav navbar-nav pull-right'>
			    <li class="last-menu"><a href="#">
			    	<i class="fa fa-clock-o" style='color: green;'></i> 10:52:09 PM-5/8/2014</a></li>
	    <li><a target="_blank" href="/cong-tac-vien.html">
	    	<i class='fa fa-users'></i> Cộng tác viên</a></li>
	    <li><a href="/nha-phan-phoi.html"><span style="color:red;  ">Nhà phân phối</span></a></li>
	    <li><a href="/dat-hang.html"><span style="color:red;  ">Đặt hàng</span></a></li>
	    <li><a href="/ho-tro-truc-tuyen.html"> <i class='fa fa-comments'></i>  Hỗ trợ trực tuyến</a></li>
	    <li><a href="#"><span style="color:red;">HOTLINE :04 2200 1100</span></a></li>
				</ul>
	          </div>
	          <div id='ul-nav-menu'>
		          <ul class="nav navbar-nav" id='left-main-menu' >
                     <li>
		                <a href="http://gss.local/" 
		            		style='font-size: 24px;'>
            		<i class='fa fa-home'></i>
            	</a>
            </li> 
            <li class='dropdown hover '>
            	<a data-toggle="dropdown" 
            	class="dropdown-toggle" 
            		role="button" href="#" 
            	>
                <i class='fa fa-check'></i>
                Giới thiệu
            	<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
    	           <li style='width:100%;'>
        	               <a href='/tam-nhin-muc-tieu.html'>
        	               	Tầm nhìn, mục tiêu
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
        	               <a href='/gia-tri-cot-loi.html'>
        	               	Giá trị cốt lõi
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
        	               <a href='/hinh-anh-hoat-dong.html'>
        	               	Hình ảnh hoạt động
        	               </a>
    	           </li>
	           </ul>
	           
            </li>
            
            <li>
                <a href="/doi-tac-va-khach-hang.html" >
            		<i class="fa fa-user"></i> Đối tác & Khách hàng</a>
            </li>          

	       <li class='dropdown hover '>
	           <a data-toggle="dropdown" 
            		class="dropdown-toggle" 
            			role="button" href="#">
            			Sản phẩm & dịch vụ
	           <span class="caret"></span>
	           </a>
	           <ul class="dropdown-menu" role="menu">
    	           <li style='width:100%;'>
        	               <a href='/phan-mem-ke-toan.html'>
        	               	Phần mềm kế toán
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
        	               <a href='/giai-phap-nganh-xay-dung.html'>
        	               	Giải pháp ngành xây dựng
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
        	               <a href='/giai-phap-quan-ly-thiet-bi-truong-hoc.html'>
        	               	Giải pháp quản lý thiết bị trường học
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
        	               <a href='/giai-phap-quan-ly-khach-san.html'>
        	               	Giải pháp quản lý khách sạn
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
        	               <a href='/giai-phap-quan-ly-duoc-pham.html'>
        	               	Giải pháp ngành dược phẩm
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
        	               <a href='/giai-phap-nganh-thoi-trang.html'>
        	               	Giải pháp ngành thời trang
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
		        	               <a href='/giai-phap-ERP.html'>
		        	               	Giải pháp ERP
		        	               	</a>
        	               	</li>
       	               	</ul>
       	               	 </li>
		
			       <li class='dropdown hover '>
			           <a href="/huong-dan-va-download.html" >
		            			<i class="fa fa-download"></i> Hướng dẫn & Download</a>
			       </li>
			       
			       <li class='dropdown hover '>
			           <a data-toggle="dropdown" 
		            	class="dropdown-toggle" 
		            		role="button" href="#" >Video
		            		<span class='caret'></span></a>
		            		
		            		<ul class="dropdown-menu" role="menu">
		            		<li style='width:100%;'>
        	               <a href='/clip-hai.html'>
        	               	Clip hài
        	               </a>
    	           </li>
    	           <li style='width:100%;'>
		        	               <a href='/clip-huong-dan-phan-mem.html'>
		        	               	Hướng dẫn phần mềm
		        	               	</a>
        	               	</li>
       	               	</ul>
			       </li>
		
				  <?php if (has_perm('sudo')) :?>
				  <li style="float:right">
		            <i class='icon-off'></i> <a href="/user/logout">Log out</a>
		            </li>
		
		            <li style="float:right">
		            <a href='/user/<?php echo $lu['id'];?>'><i class="icon-user"></i> <?php echo $lu['name']?></a> 
		            
		            </li>
						  
		 			<li class="pull-right">
						<a href="/site/admin"><i class='icon-legal' style="color:red"></i>Admin</a>
		          	</li>
		            <?php endif;?>
		          </ul>
	          </div>
	          
	          
	        </div><!--/.nav-collapse -->	
    </div>